### ISSUE TITLE
Remove redalert.ini check in Main

### ISSUE THREAD

**Issue by tomsons26** [TheAssemblyArmada/Chronoshift#23]
WinMain checks for "REDALERT.INI" which is redundant on the Windows version.
Reason for this logic is cause in DOS you HAD to run SETUP before you could start the game cause SETUP set up the sound configuration. This config, while read, isn't actually used by the Windows version.

Removing this check will solve first run freezes as the game gets stuck looking for the ini.
We should write a new ini instead if none exists.

**Comment by ghost** [comment]
Issue fixed in #144 .
