### ISSUE TITLE
All compiled files receive git information

### ISSUE THREAD

**Issue by janisozaur** [TheAssemblyArmada/Chronoshift#6]
https://github.com/TheAssemblyArmada/Chronoshift/blob/8b419b1c1e017766d5c505f994283fa988205570/CMakeLists.txt#L135

Please do not add such code, it prevents things like ccache, PCH, etc.

Consider using a dedicated file and only setting such options for that one target. See https://github.com/OpenRCT2/OpenRCT2/pull/6538 for inspiration.

**Comment by OmniBlade** [comment]
Thanks for the heads up, I'll look into this when I look at refactoring our CMake stuff for both Chronoshift and Thyme.
